### ISSUE TITLE
killaura

### ISSUE THREAD

**Issue by Hikari0964** [VapuClient/VapuLite#2]
我在学校，用老师的手机，所以不能qq聊天。killaura有问题，看看github action的提示修复一下，可能还有冗余的文件，等我18天后回去改，每天中午我都会看github owo

**Comment by Hikari0964** [comment]
好！

**Comment by Hikari0964** [comment]
越来越牛逼了啊咱们的端

**Comment by Hikari0964** [comment]
还有我可能24号回去

**Comment by Hikari0964** [comment]
卧槽家人怎么把github action删了

**Comment by Hikari0964** [comment]
爬了，等我回去修点语法错误顺便录个视频宣传宣传

**Comment by cubk** [comment]
NoCommand早就整完了，所有Command执行之前都会检查NoCommand是不是开了

**Comment by cubk** [comment]
TargetStafe不会整

**Comment by cubk** [comment]
杀戮的各种沙比问题终于修好了

**Comment by Hikari0964** [comment]
等我回去写targetstrafe

**Comment by Hikari0964** [comment]
我觉得咱们还需要一个dev

**Comment by Hikari0964** [comment]
话说为什么包名改成net.optifine了

**Comment by Hikari0964** [comment]
我走咯

**Comment by cubk** [comment]
报名改optifine是因为如果用siminject把注入有客户端反作弊的服务器客户端里会被检测，报名改成optifine就会被识别成of，就不检测了

**Comment by 493505110** [comment]
![CF310C6F45F8BE72F4BD7FE0BD9C88F9](https://user-images.githubusercontent.com/29498336/158996296-55cd01ef-8d52-41d4-9382-81bfbe4e90d9.png)

**Comment by cubk** [comment]
> ![CF310C6F45F8BE72F4BD7FE0BD9C88F9](https://user-images.githubusercontent.com/29498336/158996296-55cd01ef-8d52-41d4-9382-81bfbe4e90d9.png)

 ![CF310C6F45F8BE72F4BD7FE0BD9C88F9](https://user-images.githubusercontent.com/29498336/158996296-55cd01ef-8d52-41d4-9382-81bfbe4e90d9.png)

**Comment by Hikari0964** [comment]
明天老师手机没流量了，好在我4days以后就回去了

**Comment by Hikari0964** [comment]
回去看看能不能注入网易

**Comment by cubk** [comment]
> 回去看看能不能注入网易

现在还是不行

**Comment by Hikari0964** [comment]
啊这

**Comment by Hikari0964** [comment]
我回去写cloud的后端？

**Comment by Hikari0964** [comment]
手机还给老师了，owo

**Comment by Hikari0964** [comment]
4days后再见
