### ISSUE TITLE
2.1.2无法注入

### ISSUE THREAD

**Issue by talting** [VapuClient/VapuLite#4]
[图](https://message.biliimg.com/bfs/im/4a2dc18771939d75d59e1c5bfabb983716c3d1e2.png)
2.0可以注入2.1.2就不行了

**Comment by mckuhei** [comment]
你试试用[这个jar](https://github.com/VapuClient/VapuLite/suites/5726462941/artifacts/189441501)搭配下[SimInject](https://github.com/McModuleStudio/SimInject)

**Comment by talting** [comment]
666注入了
